package main
//GENERATED BY EVO-NG
import (
	"github.com/getevo/evo-ng"
	"github.com/getevo/examples/sample/http"
	"github.com/getevo/examples/sample/apps/geoip"
	"github.com/getevo/examples/sample/apps/myapp"
	"github.com/getevo/examples/sample/apps/override"
	"github.com/getevo/evo-ng/apps/redis"
)

func main() {
	//Register EVO
	evo.Engine()

	evo.UseContext(&http.Context{})
	OverRide()
	Register()
	Router()
	evo.Run(Ready)
}
func OverRide() {
	evo.Register(override.OverRide)
}
func Register() {
	evo.Register(geoip.Register)
	evo.Register(myapp.Register)
	evo.Register(redis.Register)
}
func Ready() {
	evo.Register(myapp.Ready)
}
func Router() {
	evo.Register(myapp.Router)
}
